name: 'secret'
version: '1.0.0'
config-version: 2

profile: default

vars:
  my_cool_var: '2016-06-01'
  disable_models: "['some_model_name']"
  snowflake_meta_src_db: 'snowflake' # override this with -> dbt run --vars "'snowflake_meta_src_db': 'my_snowflake_meta_src_db'"
  dbt_artifacts_database: development
  dbt_artifacts_schema: dbt_artifacts_kearns_added
  source_database: 'raw'
  target_database: 'raw'
  schemas: {'dev': ['dev_schema', 'dev_test']}
  run_date: '1970-01-01'

models:
  secret:
    +materialized: view
    +meta:
      some_key: some_value
    
    snowflake_meta:
      +tags:   snowflake_meta
      +schema: snowflake_meta

    demos:
      custom_schema:
        +schema:       custom_schema  
        +materialized: table  
      netflix:
        +tags:    netflix
        +schema:  netflix
        +enabled: false
      easy_incremental:
        +watermark:    watermark
        +materialized: easy_incremental
      hard_deletes:
        +enabled: True
  
  dbt_artifacts:
    +schema: dbt_artifacts_kearns_added
    staging:
      +schema: dbt_artifacts_kearns_added__staging

sources:
  secret:
    snowflake_meta:
      +tags: ['snowflake_meta']
    hard_deletes:
      +enabled: True

snapshots:
  secret:
    snowflake_meta:
      +tags: ['snowflake_meta']
      +target_schema: "{{ 'snowflake_meta' if 'prod' in target.name.lower() else target.schema ~ '__snowflake_meta' }}"

    hard_deletes:
      +enabled: True

on-run-start:
  # - "{{ create_run_end_results_table() }}"

on-run-end:
  # - "{{ log_run_end_results(results) }}"  # JYeo code
  # - "{{ dbt_artifacts.upload_results(results) }}"  # dbt_artifacts
  # - "{{ store_test_results(results) }}" # store test failures
