
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  my_cool_var: '2016-06-01'
  dbt_system_to_build: 'incremental'
  weekday_sale_default_weekday: thursday
  weekday_sale:
    - weekday: monday
      promotion_no: 18015
      sp_sales_code: 512
      media_mark: 18251
    - weekday: tuesday
      promotion_no: 18019
      sp_sales_code: 517
      media_mark: 18046
    - weekday: wednesday
      promotion_no: 18061
      sp_sales_code: 518
      media_mark: 17771
    - weekday: thursday
      promotion_no: 18064
      sp_sales_code: 519
      media_mark: 18474
    - weekday: friday
      promotion_no: 18044
      sp_sales_code: 520
      media_mark: 18256


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
    # Applies to all files under models/example/
    +labels:
      test_label: "yes"
      invocation_id: "{{ invocation_id }}"
    example:
      materialized: view
