version: 2

models:
  - name: model_with_schema_tests
    config:
      meta:
        loader: snowflake
    columns:
      - name: id
        config:
          tags:
            - skippable_schema_test
        tests:
          - unique
          - not_null

